SimpleBitmapLibrary: PixelData_24_Bit Class Reference
PixelData_24_Bit Class Reference
#include <Pixel_24.h>
Public Member Functions
PixelData_24_Bit ()
PixelData_24_Bit (char b, char g, char r)
PixelData_24_Bit & operator= (const PixelData_24_Bit &rhs)
bool operator== (const PixelData_24_Bit &rhs)
bool operator!= (const PixelData_24_Bit &rhs)
char * pack_pixel ()
void set (char, char, char)
void blue (char)
void green (char)
void red (char)
char blue () const
char green () const
char red () const
Detailed Description
Represents a single 24-bit pixel
Constructor & Destructor Documentation
PixelData_24_Bit::PixelData_24_Bit () [inline]
Empty constructor. Defaults red, green, and blue to 0x00, and write_length to 24.
                          : PixelData(3), v_blue(0x00), v_green(0x00), v_red(0x00),
                        is_packed(false) { }
PixelData_24_Bit::PixelData_24_Bit (char b, char g, char r) [inline]
Constructor. Defaults red, green, and blue to passed values and write_length to 24.
                                                : PixelData(3), v_blue(b), v_green(g),
                        v_red(r), is_packed(false) { }
Member Function Documentation
void PixelData_24_Bit::blue (char value)
Set the blue value of the pixel.
Parameters:
value The blue value to set
{
        v_blue = value;
        is_packed = false;
}
char PixelData_24_Bit::blue () const
Get the blue value of the pixel.
Returns:
The blue value of the pixel
Referenced by operator=(), and set().
{
        return v_blue;
}
char PixelData_24_Bit::green () const
Get the green value of the pixel.
Returns:
The green value of the pixel
Referenced by operator=(), and set().
{
        return v_green;
}
void PixelData_24_Bit::green (char value)
Set the green value of the pixel.
Parameters:
value The green value to set
{
        v_green = value;
        is_packed = false;
}
bool PixelData_24_Bit::operator!= (const PixelData_24_Bit & rhs)
Determine if this pixel24 is not equal to another pixel24.
Parameters:
rhs The right hand side of the equality.
Returns:
True if they are not the same. False otherwise.
{
        return !(*this == rhs);
}
pixel24 & PixelData_24_Bit::operator= (const PixelData_24_Bit & rhs)
Set this pixel24 equal to another pixel24.
Parameters:
rhs The right hand side of the equality.
Returns:
This pixel24.
References BMPFile_24bit_PixelData::blue, blue(), BMPFile_24bit_PixelData::green, green(), BMPFile_24bit_PixelData::red, and red().
{
        blue(rhs.blue());
        green(rhs.green());
        red(rhs.red());
        return *this;
}
bool PixelData_24_Bit::operator== (const PixelData_24_Bit & rhs)
Determine if this pixel24 is equal to another pixel24.
Parameters:
rhs The right hand side of the equality.
Returns:
True if they are the same. False otherwise.
References BMPFile_24bit_PixelData::blue, BMPFile_24bit_PixelData::green, and BMPFile_24bit_PixelData::red.
{
        return (v_blue == rhs.blue()) && (v_green == rhs.green()) && (v_red == rhs.red());
}
char * PixelData_24_Bit::pack_pixel () [virtual]
Implimentation of required pack_pixel() function.
Packs the pixel data into a char array and returns it. 24-bit pixel data is contained in 3 bytes so the return array is 3 chars long (blue, green, red).
Implements PixelData.
{
        if (!is_packed)
        {
                packed_pixel_data[0] = v_blue;
                packed_pixel_data[1] = v_green;
                packed_pixel_data[2] = v_red;
                is_packed = true;
        }
        return packed_pixel_data;
}
char PixelData_24_Bit::red () const
Get the red value of the pixel.
Returns:
The red value of the pixel
Referenced by operator=(), and set().
{
        return v_red;
}
void PixelData_24_Bit::red (char value)
Set the red value of the pixel.
Parameters:
value The red value to set
{
        v_red = value;
        is_packed = false;
}
void PixelData_24_Bit::set (char blue, char green, char red)
Set the color data of the pixel.
Parameters:
red The red value of the pixel in hex.
green The green value of the pixel in hex.
blue The blue value of the pixel in hex.
References blue(), green(), and red().
{
        this->v_blue = blue;
        this->v_green = green;
        this->v_red = red;
        is_packed = false;
}
The documentation for this class was generated from the following files:
src/Pixel_24/Pixel_24.h
src/Pixel_24/Pixel_24.cpp