SimpleBitmapLibrary: PixelArray Class Reference
PixelArray Class Reference
#include <PixelArray.h>
Public Member Functions
PixelArray ()
PixelArray (int, int, pixel *)
int Rows ()
int Columns ()
int Packed_Array_Length ()
void Resize_PixelArray (int, int)
pixel * get (int, int)
void set (int, int, pixel *)
void setEmpty (pixel *)
char * pack_pixel_array ()
~PixelArray ()
Constructor & Destructor Documentation
PixelArray::PixelArray ()
Empty constructor for STL support
{
        rows = 0;
        columns = 0;
        row_padding = 0;
        packed_pixel_array = 0;
        packed_array_length = 0;
        empty = 0;
        pixel_array_is_packed = false;
}
PixelArray::PixelArray (int height, int width, pixel * empty)
Make a new PixelArray with a set height and width.
Parameters:
height The height of the bitmap in pixels
width The width of the bitmap in pixels
empty The array's default empty pixel data
References Resize_PixelArray(), and setEmpty().
{
        packed_pixel_array = 0;
        Resize_PixelArray(height, width);
        setEmpty(empty);
}
PixelArray::~PixelArray ()
Destroys packed_pixel_array.
{
        if (packed_pixel_array != 0)
                delete[] packed_pixel_array;
        un_init_pixel_data_array();
}
Member Function Documentation
int PixelArray::Columns ()
Get the number of columns in the bitmap.
Returns:
The number of columns of pixel data
Referenced by Pixel_Array_Test::EmptyConstructorTest(), and Pixel_Array_Test::IntIntPixelPointer_ConstructorTest().
{
        return columns;
}
pixel * PixelArray::get (int row, int col)
Returns the a pixel object at a passed coordinate.
Parameters:
row The row position of the requested pixel
col The column position of the requested pixel
Returns:
The pixel at row x col
{
        //return pixel_array.at(rowCol.first).at(rowCol.second);
        return pixel_array[getPosition(rowCol)];
}
char * PixelArray::pack_pixel_array ()
Pack and return the Pixel Array data
Returns:
The packed pixel array
References PixelData::pack_pixel(), and PixelData::write_length.
Referenced by test_new().
{
        if (!pixel_array_is_packed)
        {
                int pixel_len = empty->write_length;
                char *packed_pixel = 0;
                packed_array_length = (columns + row_padding) * rows * pixel_len;
                packed_pixel_array = new char[packed_array_length];
                pair<int,int> coords;
                int row, col;
                for (int packed_i = 0; packed_i < packed_array_length; packed_i += pixel_len)
                {
                        coords = calc_pixel_coords_by_packed_index(packed_i);
                        row = coords.first;
                        col = coords.second;
                        packed_pixel = col < columns ? get(row, col)->pack_pixel() : empty->pack_pixel();
                        move_data_into_packed_array(packed_pixel, packed_i, pixel_len);
                }
                pixel_array_is_packed = true;
        }
        return packed_pixel_array;
}
int PixelArray::Packed_Array_Length ()
Return the length of the fully packed pixel array (char array). Includes empty pixel data used for padding.
Returns:
The length of the pixel data array.
Referenced by Pixel_Array_Test::EmptyConstructorTest(), and Pixel_Array_Test::IntIntPixelPointer_ConstructorTest().
{
        return packed_array_length;
}
void PixelArray::Resize_PixelArray (int height, int width)
Resize the PixelArray to a new size.
Parameters:
height The height of the bitmap in pixels
width The width of the bitmap in pixels
Referenced by PixelArray().
{
        rows = height;
        columns = width;
        row_padding = columns % 4;
        if (packed_pixel_array != 0)
        {
                delete[] packed_pixel_array;
        }
        packed_array_length = 0;
        packed_pixel_array = 0;
        pixel_array_is_packed = false;
        init_pixel_data_array();
        row_offsets.reserve(rows);
}
int PixelArray::Rows ()
Get the number of rows in the bitmap. Does not count padding.
Returns:
The number of rows of pixel data
Referenced by Pixel_Array_Test::EmptyConstructorTest(), and Pixel_Array_Test::IntIntPixelPointer_ConstructorTest().
{
        return rows;
}
void PixelArray::set (int row, int col, pixel * p)
Set a pixel object to a specific row and column in the PixelArray
Parameters:
row The row position of the pixel data
col The column position of the requested pixel data
p The pixel data to set
Referenced by test_new().
{
        pixel_array[getPosition(rowCol)] = pixel;
}
void PixelArray::setEmpty (pixel * new_empty)
Set the empty pixel data.
Parameters:
new_empty The empty pixel data
Referenced by PixelArray().
{
        empty = new_empty;
        pixel_array_is_packed = false;
}
The documentation for this class was generated from the following files:
src/PixelArray/PixelArray.h
src/bmp.cpp
src/PixelArray/PixelArray.cpp