SimpleBitmapLibrary: Pixel_Array_Test Class Reference
Pixel_Array_Test Class Reference
#include <PixelArrayTest.h>
Public Member Functions
void setUp (void)
void tearDown (void)
void EmptyConstructorTest (void)
void IntIntPixelPointer_ConstructorTest (void)
void RowsTest (void)
void ColumnsTest (void)
void PackedArrayLengthTest (void)
void IntIntResize_PixelArrayTest (void)
void IntIntGetTest (void)
void IntIntSetTest (void)
void PixelSetEmptyTest (void)
void PackPixelParrayTest (void)
Member Function Documentation
void Pixel_Array_Test::ColumnsTest (void)
{
        CPPUNIT_ASSERT(true);
}
void Pixel_Array_Test::EmptyConstructorTest (void)
References PixelArray::Columns(), PixelArray::Packed_Array_Length(), and PixelArray::Rows().
{
        pixel_array t_pa;
        CPPUNIT_ASSERT(t_pa.Rows() == 0);
        CPPUNIT_ASSERT(t_pa.Columns() == 0);
        CPPUNIT_ASSERT(t_pa.Packed_Array_Length() == 0);
}
void Pixel_Array_Test::IntIntGetTest (void)
{
        CPPUNIT_ASSERT(true);
}
void Pixel_Array_Test::IntIntPixelPointer_ConstructorTest (void)
References PixelArray::Columns(), PixelArray::Packed_Array_Length(), and PixelArray::Rows().
{
        char err_buff[255];
        int rows = 3;
        int columns = 3;
        int packed_length = 0;
        pixel_array t_pa(rows, columns ,&black);
        sprintf(err_buff,
                "The assertion 0 == %d failed. Got %d == %d instead.",
                packed_length, t_pa.Packed_Array_Length(), packed_length);
        CPPUNIT_ASSERT(t_pa.Rows() == rows);
        CPPUNIT_ASSERT(t_pa.Columns() == columns);
        CPPUNIT_ASSERT_MESSAGE(err_buff, t_pa.Packed_Array_Length() == packed_length);
}
void Pixel_Array_Test::IntIntResize_PixelArrayTest (void)
{
        CPPUNIT_ASSERT(true);
}
void Pixel_Array_Test::IntIntSetTest (void)
{
        CPPUNIT_ASSERT(true);
}
void Pixel_Array_Test::PackedArrayLengthTest (void)
{
        CPPUNIT_ASSERT(true);
}
void Pixel_Array_Test::PackPixelParrayTest (void)
{
        CPPUNIT_ASSERT(true);
}
void Pixel_Array_Test::PixelSetEmptyTest (void)
{
        CPPUNIT_ASSERT(true);
}
void Pixel_Array_Test::RowsTest (void)
{
        CPPUNIT_ASSERT(true);
}
void Pixel_Array_Test::setUp (void)
{
        white.set(0,0,0);
        black.set(255,255,255);
}
void Pixel_Array_Test::tearDown (void)
{}
The documentation for this class was generated from the following files:
src/unit/PixelArrayTest.h
src/unit/PixelArrayTest.cpp