SimpleBitmapLibrary: src/writeBitmap.cpp File Reference
src/writeBitmap.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <string>
#include <memory>
#include <boost/cstdint.hpp>
#include "PixelArray.h"
#include "Pixel_24.h"
Functions
void printPixel (pixel24 *p24)
void printPixelCharArray (char *data, int write_length)
int test_old ()
int test_new ()
int m ()
Function Documentation
int m ()
References test_new().
{
        //return test_old();
        return test_new();
}
void printPixel (pixel24 * p24)
References BMPFile_24bit_PixelData::blue, BMPFile_24bit_PixelData::green, and BMPFile_24bit_PixelData::red.
{
        cout << setw(2) << hex << setfill('0') << p24->blue << " " <<
                        setw(2) << hex << setfill('0') << p24->green << " " <<
                        setw(2) << hex << setfill('0') << p24->red << endl;
}
void printPixelCharArray (char * data, int write_length)
{
        for (int x = 0; x < write_length; x++)
                cout << setw(2) << hex << setfill('0') << data[x] << " ";
        cout << endl;
}
int test_new ()
References PixelArray< pixeltype >::pack_pixel_array(), and PixelArray< pixeltype >::set().
Referenced by m().
{
        //pixel24 pix(0x01, 0x6F, 0x5A);
        //printPixelCharArray(pix.pack_pixel(), pix.write_length);
        //printPixelCharArray(data, 3);
        PixelArray pa(4, 4);
        pixel24 black(0x00, 0x00, 0x00), white(0xFF, 0xFF, 0xFF);
        pa.set(0, 0, &black);
        pa.set(1, 1, &black);
        pa.set(2, 2, &black);
        pa.set(3, 3, &black);
        char *sp = pa.pack_pixel_array(&white);
        for (int x = 0; x < pa.packed_array_length; x++)
                printf("i = %d => %x", x, sp[x]);
        return 0;
}
int test_old ()
{
        /*
        int height = 3;
        int width = 3;
        string filename = "test.bmp";
        //pixel24_array pixarr(height, width);
        BMP24 bmp(filename, height, width);
        char min = 0x00;
        char max = 0xff;
        pixel24 blue(max,min,min), green(min,max,min), red(min,min,max);
        pair<int,int> rowCol(0,0);
        bmp.set(blue,rowCol);
        rowCol.second = 1;
        bmp.set(green,rowCol);
        rowCol.second = 2;
        bmp.set(red,rowCol);
        bmp.Write_Bitmap();
        */
        return 0;
}